### ISSUE TITLE
Possible to resume migration from certain point?

### ISSUE THREAD

**Issue by unor** [Dahie/caramelize#10]
I tried to migrate a WikkaWiki database (the .sql file has a size of ~ 965 MB).

caramelize ran for 26 hours (in this time, it used all of my available RAM ~ 13 GB, and my complete swap  ~ 14 GB), and it managed to migrate "(49637/63226)" before the process got killed. 

Is there a way to resume the migration from this point?

I fear that the process will again get killed before completion if I’d have to start from the beginning.

**Comment by Dahie** [comment]
Oh, respect for that wiki size. I'll have to look into it, but by default there is no way. I'll think about it.

**Comment by Dahie** [comment]
Actually it's not to hard. You can run a slightly changed version of the WikkaWiki adapter in which you modify the query to your database. For this you create a new custom wiki adapter. Create a `wikka_wiki_resume_progress_at_id.rb` in the directory where you run caramelize and add this content: 

```
require 'caramelize/input_wiki/wiki'
require 'caramelize/input_wiki/wikkawiki'

# Within this method you can define your own Wiki-Connectors to Wikis
# not supported by default in this software

def input_wiki

  options = { host: "localhost",
              username: "user",
              database: "database_name",
              password: 'admin_password',
              markup: :wikka,
              filters: [ Caramelize::Wikka2Markdown]
            }

  wiki = Caramelize::InputWiki::Wiki.new(options)
  wiki.instance_eval do
    def read_pages
      start_progress_at_id = 47

      sql = "SELECT id, tag, body, time, latest, user, note FROM wikka_pages WHERE id > #{start_progress_at_id} ORDER BY time;"
      results = database.query(sql)
      results.each do |row|
        titles << row["tag"]
        author = authors[row["user"]]
        properties = { id: row["id"],
                       title: row["tag"],
                       body: row["body"],
                       markup: :wikka,
                       latest: row["latest"] == "Y",
                       time: row["time"],
                       message: row["note"],
                       author: author,
                       author_name: row["user"] }

        page = Caramelize::Page.new(properties)
        revisions << page
      end
      titles.uniq!
      revisions
    end
  end

  wiki
end
```



Modify the database credentials in the `options` and change the `start_progress_at_id` id in line 25 to the last id that was successfully imported in your first run.
Now run in your console:

    $ caramelize run -c wikka_wiki_resume_progress_at_id.rb

It will prompt you if you want to overwrite the existing with a fresh repository, deny that.
It should continue to process your wiki and append to the git repository you created on the first run.

Let me know if it works. Good luck!

**Comment by Dahie** [comment]
Oh, by the way, by changing the SQL-query in line 27, you can also manually batch your export by defining id ranges you want to export.

**Comment by Dahie** [comment]
This is the same solution but with shorter code:

```
require 'caramelize/input_wiki/wikkawiki'

# Within this method you can define your own Wiki-Connectors to Wikis
# not supported by default in this software

def input_wiki
  options = { host: "localhost",
              username: "user",
              database: "database_name",
              password: 'admin_password',
              home_page_title: 'dahie',
            }

  wiki = Caramelize::InputWiki::WikkaWiki.new(options)
  wiki.instance_eval do
    def pages
      start_progress_at_id = 47

      sql = "SELECT id, tag, body, time, latest, user, note FROM wikka_pages WHERE id > #{start_progress_at_id} ORDER BY time;"
      @pages ||= database.query(sql)
    end
  end

  wiki
end

```

**Comment by unor** [comment]
I tested the [first variant](https://github.com/Dahie/caramelize/issues/10#issuecomment-736398690). It worked great!

Thank you so much for the solution, and for your quick response, Dahie :)

**Comment by Dahie** [comment]
Alright, it worked!

I'll close this issue. If you find a problem in the wikka wiki conversion, make a new one, please. :)
